export const contentHorizontalPadding = 9.375;
export const contentHorizontalPaddingMedium = contentHorizontalPadding / 2;
export const contentHorizontalPaddingSmall = contentHorizontalPadding / 4;
export const newWidth = 47.5;
export const newWidthSmall = 100;
export const linkPadding = 1;
export const linkPaddingSmall = linkPadding / 2;
export const linkLeftPadding = 2;
export const linkLeftPaddingSmall = 1;